version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  #install:
    #commands:
      # - command
      # - command
  pre_build:
    commands:
        - aws ecr get-login --no-include-email --region us-west-2
      # - command
  build:
    commands:
        - docker build -t 590217768757.dkr.ecr.us-west-2.amazonaws.com/aviva-ecr:latest .
      # - command
  post_build:
    commands:
        - docker push 590217768757.dkr.ecr.us-west-2.amazonaws.com/aviva-ecr:latest
      # - command
#artifacts:
  #files:
    # - location
    # - location
  #discard-paths: yes
  #base-directory: location

