version: 0.2

phases:
  build:
    commands:
      - docker build -t aviva-ecr .
      - docker tag aviva-ecr:latest 590217768757.dkr.ecr.us-west-2.amazonaws.com/aviva-ecr:latest
      - docker push 590217768757.dkr.ecr.us-west-2.amazonaws.com/aviva-ecr:latest
